name: deploy
on:
  push:
    branches:
      - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: yarn install
      - name: quality gates
        run: yarn run test
      - name: build
        run: yarn run build
      - name: deploy
        run: |
          git config --global user.email "njkznu@gmail.com"
          git config --global user.name "kuzanatoliy"
          git add -f build
          git commit -am "deploy to gh-pages"
          git push origin `git subtree split --prefix dist`:refs/heads/gh-pages --force
          git reset --hard HEAD~1
