name: prod deploy
on:
  push:
    branches:
      - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: yarn install
      - name: quality gates
        run: yarn run test
      - name: build
        run: yarn run build
      - name: deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.x29852yf.beget.tech
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build
          server-dir: test
